version: '3.4'
services:
  rezerwacje-app:
    build: ./rezerwacje-app
    # container_name: rezerwacje-app
    ports: 
      - 8080:8080
    volumes: 
      - ./rezerwacje-app:/app
    user: appuser
    env_file: .env
    command: ./gradlew --project-cache-dir /tmp/gradle-chache bootRun
    depends_on:
      - rezerwacje-db
    networks:
      - backend
      - frontend

  rezerwacje-front:
    build:
      context: ./rezerwacje-front
      target: base
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./rezerwacje-front/public:/webapp/public
      - ./rezerwacje-front/src:/webapp/src
      - ./rezerwacje-front/package.json:/webapp/package.json
      - ./rezerwacje-front/package-lock.json:/webapp/package-lock.json
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    networks:
      - frontend

  rezerwacje-db:
    image: postgres
    env_file: .env
    environment:
      - PGDATA=/db/data
    ports:
      - 5432:5432
    volumes:
      - ./rezerwacje-db/data:/db/data
    networks:
      - backend

networks:
  backend:
  frontend:

