version: '3.4'
services:
  rezerwacje-app:
    build: 
      context: ./rezerwacje-app
      target: base
    # container_name: rezerwacje-app
    ports: 
      - 8080:8080
    volumes: 
      - ./rezerwacje-app:/app
    user: appuser
    env_file: .env
    environment:
      - PORT=8080
      - JDBC_DATABASE_URL=postgresql://rezerwacje-db:5432/${POSTGRES_DB}
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
    depends_on:
      - rezerwacje-db
    networks:
      - backend
      - frontend

  rezerwacje-front:
    build:
      context: ./rezerwacje-front
      target: base
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./rezerwacje-front/public:/webapp/public
      - ./rezerwacje-front/src:/webapp/src
      - ./rezerwacje-front/package.json:/webapp/package.json
      - ./rezerwacje-front/package-lock.json:/webapp/package-lock.json
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    depends_on:
      - rezerwacje-app
    networks:
      - frontend

  rezerwacje-db:
    image: postgres:11.7
    env_file: .env
    environment:
      - PGDATA=/db/data
    ports:
      - 5432:5432
    volumes:
      - db-data:/db/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
