export { default as Home } from "./Home";
export { default as Rooms } from "./Rooms";
export { default as Courses } from "./CoursesOfStudy";
export { default as Exams } from "./Exams";
export { default as Users } from "./Users";
export { default as Recruitments } from "./Recruitments";
export { default as UserCourses } from "./UserCourses";
export { default as Schedule } from "./Schedule";
export { default as Login } from "./Login/login.component"
